# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/microsoft_phi15_project',
                'doc_host': 'https://nvtai040502.github.io',
                'git_url': 'https://github.com/nvtai040502/microsoft_phi15_project',
                'lib_path': 'microsoft_phi15_project'},
  'syms': {'microsoft_phi15_project.core': {'microsoft_phi15_project.core.foo': ('core.html#foo', 'microsoft_phi15_project/core.py')}}}
